# H2 DB
spring.datasource.url=jdbc:h2:tcp://localhost/~/gahih
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA dev
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf dev
spring.thymeleaf.cache=false

# Error dev
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=on_param

# File dev
file.upload-dir=D:/gahih-uploads

# Logging dev
logging.level.root=info
logging.level.com.gahih=debug
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace