# MySQL DB
spring.datasource.url=${GAHIH_DB_URL}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${GAHIH_DB_USERNAME}
spring.datasource.password=${GAHIH_DB_PASSWORD}

# H2 console off
spring.h2.console.enabled=false

# JPA prod
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Thymeleaf prod
spring.thymeleaf.cache=true

# Error prod
server.error.include-message=never
server.error.include-binding-errors=never
server.error.include-stacktrace=never

# File prod
file.upload-dir=${GAHIH_UPLOAD_DIR}

# Logging prod
logging.level.root=info
logging.level.com.gahih=info
logging.level.org.hibernate.SQL=off
logging.level.org.hibernate.orm.jdbc.bind=off
logging.level.org.springframework.security=warn